---

- name: Install dev tool apt packages
  apt:
    pkg:
    - build-essential
    - clang-format
    - cmake
    - curl
    - jq
    - libclang-dev
    - openjdk-17-jdk-headless
    - sshfs
    - wget
    - zlib1g
    - zlib1g-dev
    - zsh
  become: yes
