---

- name: Install user tool homebrew packages
  homebrew:
    name:
    - docker-compose
    - tree
    - w3m

- name: Install user tool homebrew cask packages
  homebrew_cask:
    name:
    - alfred
    - caffeine
    - discord
    - docker
    - firefox
    - firefox-developer-edition
    - iterm2
    - rectangle
    - shifty
    - spotify
    - vlc
    accept_external_apps: yes
