---

- name: Install vim apt packages
  apt:
    pkg:
    - vim-nox
  become: yes

- name: Install vim build dependencies apt packages
  apt:
    pkg:
    - libatk1.0-dev
    - libcairo2-dev
    - libgtk2.0-dev
    - liblua5.3-0-dev
    - libncurses5-dev
    - libperl-dev
    - libx11-dev
    - libxpm-dev
    - libxt-dev
    - lua5.3
    - python3-dev
    - ruby-dev
  become: yes
