---

- name: Create shell config directories
  file:
    dest: "{{shellrc_config_dir}}"
    state: directory
    mode: 0700

- name: Render Shell Vars template file
  template:
    src: vars.sh
    dest: "{{shellrc_config_dir}}/0-shellrc.sh"
    mode: 0400

- name: Copy Shell RC template file
  template:
    src: shellrc
    dest: ~/.shellrc
    mode: 0400

- name: Link Shell RC files
  file:
    src: "{{dotfiles_src_dir}}/shellrc/{{item}}"
    dest: "{{shellrc_config_dir}}/{{item}}"
    state: link
    follow: no
    force: yes
  with_items:
  - 1-pathlist.sh
  - 2-history.sh
  - 2-locale.sh
  - 3-bazel.sh
  - 3-cli-shortcuts.sh
  - 3-default-programs.sh
  - 3-git.sh
  - 3-inotify.sh
  - 3-tmux.sh
  - 3-vagrant.sh

- name: Link macOS Shell RC files
  file:
    src: "{{dotfiles_src_dir}}/shellrc/{{item}}"
    dest: "{{shellrc_config_dir}}/{{item}}"
    state: link
    follow: no
    force: yes
  with_items:
  - 2-pathlist-macos.sh
  when: ansible_os_family == "Darwin"
