---

- hosts: 127.0.0.1
  connection: local
  roles:
    - {role: alacritty, tags: [alacritty]}
    - {role: bashrc, tags: [bashrc]}
    - {role: cargo, tags: [cargo]}
    - {role: dircolors, tags: [dircolors]}
    - {role: fzf, tags: [fzf]}
    - {role: gem, tags: [gem]}
    - {role: git, tags: [git]}
    - {role: go, tags: [go]}
    - {role: npm, tags: [npm]}
    - {role: pip, tags: [pip]}
    - {role: ssh-agent-canonicalize, tags: [ssh-agent-canonicalize]}
    - {role: tmux, tags: [tmux]}
    - {role: vagrant, tags: [vagrant]}
    - {role: vim, tags: [vim]}
    - {role: worktree, tags: [worktree]}
    - {role: zshrc, tags: [zshrc]}
    - {role: work, tags: [never, work]}
