---

# TODO
# * add work role with dep on shellrc and bazel
#     link work shellrc file to `3-work.sh`
#     link work bazelrc file to `work.bazelrc`
# * add dep on shellrc to git role
#     move m and om vars from 3-work.sh to 3-git.sh
#     move g function from 3-cli-shortcuts to 3-git
#     link 3-git.sh to shellrc
- hosts: 127.0.0.1
  connection: local
  roles:
  - alacritty
  - bashrc
  - cargo
  - dircolors
  - fzf
  - gem
  - git
  - go
  - npm
  - pip
  - ssh-agent-canonicalize
  - tmux
  - vagrant
  - vim
  - worktree
  - zshrc
