---

- hosts: 127.0.0.1
  connection: local
  roles:
    - {role: alacritty, tags: [alacritty]}
    - {role: bashrc, tags: [bashrc]}
    - {role: bazel, tags: [bazel]}
    - {role: bin, tags: [bin]}
    - {role: cargo, tags: [cargo]}
    - {role: dircolors, tags: [dircolors]}
    - {role: erd, tags: [erd]}
    - {role: flatpak, tags: [flatpak]}
    - {role: fzf, tags: [fzf]}
    - {role: gem, tags: [gem]}
    - {role: git, tags: [git]}
    - {role: go, tags: [go]}
    - {role: lua, tags: [lua]}
    - {role: neovim, tags: [neovim]}
    - {role: npm, tags: [npm]}
    - {role: python, tags: [python]}
    - {role: ssh-agent-canonicalize, tags: [ssh-agent-canonicalize]}
    - {role: tmux, tags: [tmux]}
    - {role: vagrant, tags: [vagrant]}
    - {role: vim, tags: [vim]}
    - {role: worktree, tags: [worktree]}
    - {role: zshrc, tags: [zshrc]}
