---

- name: Tap homebrew repositories
  homebrew_tap:
    name: "{{item}}"
    state: present
  with_items:
  - hashicorp/tap

- name: Install dev tool homebrew packages
  homebrew:
    name:
    - clang-format
    - cmake
    - file-formula
    - git
    - git-lfs
    - golang
    - hashicorp/tap/terraform
    - ifstat
    - java
    - jq
    - less
    - libvirt
    - lua
    - neovim
    - node
    - openssh
    - pipx
    - python@3.10
    - python@3.13
    - qemu
    - reattach-to-user-namespace
    - ruby
    - screen
    - sshfs
    - tmux
    - unzip
    - vim
    - zsh

- name: Install dev tool homebrew cask packages
  homebrew_cask:
    name:
    - macfuse
    - vagrant
    accept_external_apps: yes
    sudo_password: "{{ ansible_become_pass }}"
