---

- name: Install dev tool homebrew packages
  homebrew:
    name:
    - clang-format
    - cmake
    - file-formula
    - git
    - git-lfs
    - golang
    - ifstat
    - java
    - jq
    - less
    - libvirt
    - lua
    - neovim
    - node
    - openssh
    - pipx
    - python@3.10
    - python@3.13
    - qemu
    - reattach-to-user-namespace
    - ruby
    - screen
    - tmux
    - unzip
    - vim
    - zsh

- name: Install dev tool homebrew cask packages
  homebrew_cask:
    name:
    - vagrant
    accept_external_apps: yes
    sudo_password: "{{ ansible_become_pass }}"
